id: P000C1757
initial_creation_type: input
source_metadata:
  title: Khaḍgaviṣāṇasūtra
  language: sa
  volumes:
    d372c899254d4718b9f0535594b83895:
      title: Complete text
      base_file: Complete text.txt
      work_id: WDAD646B1
  chapter_to_tile: {}
created_at: '2022-03-02T08:56:12.138501'
last_modified_at: '2022-03-02T08:56:12.138517'
